//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Entity
{
    using System;
    using System.Collections.Generic;

    public partial class COUNT
    {
        public int ID { get; set; }
        public int BOOK_ID { get; set; }
        public int TOTAL_COUNT { get; set; }
        public int CURRENT_COUNT { get; set; }
    
        public virtual BOOK BOOK { get; set; }
    }
}
