//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISSUE
    {
        public int ID { get; set; }
        public int BOOK_ID { get; set; }
        public int MEMBER_ID { get; set; }
        public System.DateTime ISSUE_DATE { get; set; }
        public System.DateTime RETURN_DATE { get; set; }
        public string ISSUED_BY { get; set; }
        public string COMMENT { get; set; }
    
        public virtual BOOK BOOK { get; set; }
        public virtual MEMBER MEMBER { get; set; }
    }
}
